create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer text not null,
  details text not null,
  total_amount numeric(12, 2) not null check (total_amount >= 0),
  paid_amount numeric(12, 2) not null default 0 check (paid_amount >= 0),
  status text not null default 'Unpaid' check (status in ('Paid', 'Partial', 'Unpaid')),
  order_date date not null,
  created_at timestamptz not null default now()
);

create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  details text not null,
  amount numeric(12, 2) not null check (amount >= 0),
  expense_date date not null,
  created_at timestamptz not null default now()
);

alter table public.orders enable row level security;
alter table public.expenses enable row level security;

drop policy if exists "Allow public read orders" on public.orders;
drop policy if exists "Allow public insert orders" on public.orders;
drop policy if exists "Allow public update orders" on public.orders;
drop policy if exists "Allow public read expenses" on public.expenses;
drop policy if exists "Allow public insert expenses" on public.expenses;
drop policy if exists "Allow logged in read orders" on public.orders;
drop policy if exists "Allow logged in insert orders" on public.orders;
drop policy if exists "Allow logged in update orders" on public.orders;
drop policy if exists "Allow logged in read expenses" on public.expenses;
drop policy if exists "Allow logged in insert expenses" on public.expenses;
drop policy if exists "Allow logged in update expenses" on public.expenses;

create policy "Allow logged in read orders"
on public.orders
for select
to authenticated
using (auth.uid() is not null);

create policy "Allow logged in insert orders"
on public.orders
for insert
to authenticated
with check (auth.uid() is not null);

create policy "Allow logged in update orders"
on public.orders
for update
to authenticated
using (auth.uid() is not null)
with check (auth.uid() is not null);

create policy "Allow logged in read expenses"
on public.expenses
for select
to authenticated
using (auth.uid() is not null);

create policy "Allow logged in insert expenses"
on public.expenses
for insert
to authenticated
with check (auth.uid() is not null);

create policy "Allow logged in update expenses"
on public.expenses
for update
to authenticated
using (auth.uid() is not null)
with check (auth.uid() is not null);
